/**
 * Vercel Build Script
 * Generates config.js from environment variables
 */

const fs = require('fs');
const path = require('path');

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.error('❌ ERROR: Missing environment variables!');
    console.error('Please set SUPABASE_URL and SUPABASE_ANON_KEY in Vercel dashboard');
    console.error('Dashboard: https://vercel.com/your-project/settings/environment-variables');
    process.exit(1);
}

// Use JSON.stringify to safely escape values
const configContent = `/**
 * ARISE Configuration
 * Auto-generated from Vercel environment variables
 * DO NOT EDIT THIS FILE MANUALLY
 */

const CONFIG = {
    SUPABASE_URL: ${JSON.stringify(SUPABASE_URL)},
    SUPABASE_ANON_KEY: ${JSON.stringify(SUPABASE_ANON_KEY)}
};

// Make available globally
if (typeof window !== 'undefined') {
    window.CONFIG = CONFIG;
}
`;

const configPath = path.join(__dirname, '..', 'config.js');

try {
    fs.writeFileSync(configPath, configContent, 'utf8');
    console.log('✅ config.js generated successfully from environment variables');
    console.log(`📝 SUPABASE_URL: ${SUPABASE_URL}`);
    console.log(`📝 SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY.substring(0, 20)}...${SUPABASE_ANON_KEY.substring(SUPABASE_ANON_KEY.length - 10)}`);
    console.log(`📄 config.js size: ${configContent.length} bytes`);
} catch (error) {
    console.error('❌ Failed to generate config.js:', error.message);
    process.exit(1);
}
